server:
  port: 8635

simbot:
  core:
    # bot qq账号和密码
    bots:

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ro635_bot?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.cgh.ro635bot.entity